### ISSUE TITLE
irgendwie klappt das noch nicht.

### ISSUE THREAD

**Issue by Oppodelldog** [Oppodelldog/pse-ui#1]
irgendwie klappt das noch nicht.
habe aktuellen sourcen gezogen und fabric, level und addLevel angepasst (btw abwärtskompatibilität klappt nicht) und habe solutionGraph angewendet. Das sieht aus wie vorher. der zielpfad wir eingezeichner aber auch "abzweiger".

Vielleicht schaust du mal nach.
Einfach npm install
und npm start. 
npm start gibt dann den port für localhost aus, wenn über docker gestartet gibt er auch die docker ip aus, cool.

@marcbreitung

**Comment by marcbreitung** [comment]
Bei der Registrierung der Renderer zu der rendererFactory hast Du für die Solution den ```ProblemGraphVisualisation.NodesRenderer``` angegeben:

```Javascript
this.canvas.rendererFactory.registerRenderer('solution', ProblemGraphVisualisation.NodesRenderer);
```
Müsset aber der ```ProblemGraphVisualisation.SolutionRenderer```

```Javascript
canvas.rendererFactory.registerRenderer('solution', ProblemGraphVisualisation.SolutionRenderer);
```

**Comment by marcbreitung** [comment]
Ich wollte eigentlich einen Pull-Request machen, hat aber nicht richtig funktioniert und die Änderung ist jetzt sofort in deinem Repository gelandet.
